FROM kalilinux/kali-linux-docker

RUN apt-get -y update 
RUN apt-get -y install net-tools && \
apt-get install -y aircrack-ng

RUN apt-get install -y pciutils

RUN apt-get install -y netdiscover
RUN apt-get -y update 
RUN apt-get install -y nmap 
RUN apt-get install -y dsniff
RUN apt-get install -y arpspoof